all: mobile_user back_office system_manager

mobile_user: mobileuserr.c
	gcc mobileuserr.c -o mobile_user -pthread

back_office: backofficee.c
	gcc backofficee.c -o back_office -pthread

system_manager: systemmanagerr.c
	gcc systemmanagerr.c -o system_manager -pthread